### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by MJMODZZ** [Fidode07/wetteransage2#1]
Schon interessant aber hab ne idee. Versuche mal das wetter laut dem standort nach zu bekommen. Ist eigentlich ziemlich einfach 

Indem du es importierst
```python
import os
```

oder einfach die ip per internet importieren
```python
 ip_address = requests.get('http://ipinfo.io/json').json()['ip']
```

dann noch eben mit dem wetterding verknüpfen

**Comment by Fidode07** [comment]
Das Code Snippet war nur zum Test, ob GitHub bei mir damals gefunkt hat. Das Repo hat eigentlich gar keinen richtigen Sinn, daher werde ich das auch nicht weiter verfolgen. Tut mir leid (Hab zurzeit einfach größere Projekte die mehr Zeit brauchen). Aber du könntest das Repo ja Forken, wenn du willst.

**Comment by MJMODZZ** [comment]
> Das Code Snippet war nur zum Test, ob GitHub bei mir damals gefunkt hat. Das Repo hat eigentlich gar keinen richtigen Sinn, daher werde ich das auch nicht weiter verfolgen. Tut mir leid (Hab zurzeit einfach größere Projekte die mehr Zeit brauchen). Aber du könntest das Repo ja Forken, wenn du willst.

Würde keinen sinn machen im endeffekt wollte ich es das du es machst

**Comment by Fidode07** [comment]
Mir war langweilig, ich hab deine Idee jetzt mal umgesetzt. Die bestimmung vom Ort ist noch bei weitem nicht Perfekt, aber an sich sollte das reichen.
